// All available case studies — matched to prospects automatically based on industry + priorities

export const CASE_STUDIES = [
  {
    id: "grown-brilliance",
    client: "Grown Brilliance",
    industry: "Luxury Jewelry · Ecommerce",
    headline: "Built a jewelry brand from zero to $200M in 18 months",
    result: "$200M",
    resultLabel: "Revenue in 18 months — from $0",
    desc: "Launched and scaled a DTC luxury jewelry brand using paid search, paid social, and AI-native creative. A $5,500 production generated $15 million in revenue.",
    quote: null,
    tags: ["ecommerce", "luxury", "jewelry", "dtc", "meta", "google", "creative", "fashion"],
  },
  {
    id: "amc-networks",
    client: "AMC Networks",
    industry: "Media · Subscriptions",
    headline: "302% YoY increase in subscriber acquisition",
    result: "302%",
    resultLabel: "YoY subscription growth",
    desc: "Rebuilt AMC's paid media strategy for subscriber acquisition across multiple streaming properties.",
    quote: { text: "Extremely knowledgeable and resourceful on all matters digital advertising.", author: "Keo Brown", role: "Marketing Director" },
    tags: ["media", "entertainment", "subscriptions", "streaming", "b2c", "google", "meta", "brand"],
  },
  {
    id: "nasdaq",
    client: "Nasdaq",
    industry: "B2B SaaS · Enterprise",
    headline: "270% increase in Sales Qualified Leads",
    result: "270%",
    resultLabel: "Increase in SQLs",
    desc: "Rebuilt Nasdaq's B2B lead generation campaigns with intent-based targeting and CRM-integrated lead scoring. Volume up dramatically — while lead quality improved simultaneously.",
    quote: null,
    tags: ["saas", "b2b", "enterprise", "lead-gen", "fintech", "crm", "google"],
  },
  {
    id: "forbes",
    client: "Forbes",
    industry: "Publishing · Brand",
    headline: "20% subscriber increase for one of the world's most iconic brands",
    result: "20%",
    resultLabel: "Subscriber growth",
    desc: "Drove measurable subscriber growth for a brand where incremental gains require precision strategy.",
    quote: { text: "They genuinely want to understand our business and help us succeed.", author: "Jessica Feintisch", role: "Marketing Director" },
    tags: ["publishing", "media", "brand", "b2c", "subscriptions", "content"],
  },
  {
    id: "wow-painting",
    client: "WOW 1 Day Painting",
    industry: "Home Services · Lead Gen",
    headline: "61% more bookings, 26% lower CPA — simultaneously",
    result: "61% + 26%",
    resultLabel: "Bookings up · CPA down",
    desc: "Rebuilt campaign architecture for this multi-location home services franchise. More bookings at a lower cost at the same time is one of the hardest things to pull off in paid media.",
    quote: null,
    tags: ["services", "home-services", "lead-gen", "franchise", "local", "google", "glsa"],
  },
  {
    id: "slinger-bag",
    client: "Slinger Bag",
    industry: "Sports Ecommerce",
    headline: "12.6X Facebook ROAS — became #1 tennis launcher in the US",
    result: "12.6X",
    resultLabel: "Facebook ROAS",
    desc: "Took an emerging sports equipment brand from unknown to market leader using a precision Meta advertising strategy. Shortlisted for New York Festivals Advertising Awards.",
    quote: null,
    tags: ["ecommerce", "sports", "consumer", "meta", "dtc", "product-launch", "brand"],
  },
  {
    id: "audioeye",
    client: "AudioEye",
    industry: "B2B SaaS · Accessibility",
    headline: "238% increase in qualified leads via ML + CRM integration",
    result: "238%",
    resultLabel: "Qualified lead increase",
    desc: "Built a machine-learning-driven lead gen system integrated directly with their CRM to filter for lead quality, not just volume.",
    quote: { text: "A partner that is vested in our success.", author: "Elsa Guerrero", role: "CMO" },
    tags: ["saas", "b2b", "accessibility", "tech", "lead-gen", "crm", "ml"],
  },
  {
    id: "rocky-mountain-decals",
    client: "Rocky Mountain Decals",
    industry: "Ecommerce · DTC",
    headline: "567% net profit increase in two months",
    result: "567%",
    resultLabel: "Net profit growth in 60 days",
    desc: "Rebuilt bidding strategy around true net profit. Within 60 days, the business was making nearly 6x more money on the same ad budget.",
    quote: null,
    tags: ["ecommerce", "dtc", "profit", "google", "shopping"],
  },
  {
    id: "yseop",
    client: "Yseop",
    industry: "Pharma · B2B",
    headline: "77% reduction in cost per lead in a highly regulated industry",
    result: "77%",
    resultLabel: "Cost per lead savings",
    desc: "Cut lead costs by more than three-quarters in pharmaceutical B2B — while improving lead quality.",
    quote: null,
    tags: ["pharma", "b2b", "regulated", "lead-gen", "healthcare", "enterprise"],
  },
  {
    id: "quantum-workplace",
    client: "Quantum Workplace",
    industry: "B2B SaaS · HR Tech",
    headline: "107% revenue growth via high-intent marketing",
    result: "107%",
    resultLabel: "Revenue growth",
    desc: "Drove consistent revenue growth through a high-intent keyword strategy and full-funnel paid approach for this HR technology platform.",
    quote: null,
    tags: ["saas", "b2b", "hr-tech", "lead-gen", "google", "enterprise"],
  },
  {
    id: "lemonlight",
    client: "Lemonlight",
    industry: "Video Production · B2B",
    headline: "302% lead growth through conversion optimization",
    result: "302%",
    resultLabel: "Lead growth",
    desc: "Rebuilt conversion strategy for a video production agency targeting B2B buyers, driving a tripling of inbound leads.",
    quote: null,
    tags: ["b2b", "creative", "video", "lead-gen", "agency", "services"],
  },
  {
    id: "panoramic-doors",
    client: "Panoramic Doors",
    industry: "B2B · High-Ticket",
    headline: "47% YoY MQL growth with 1,000% ROAS increase",
    result: "1,000%",
    resultLabel: "ROAS increase",
    desc: "Transformed paid strategy for a high-ticket B2B product, generating dramatically more qualified leads at a fraction of the previous cost.",
    quote: { text: "1000% increase in ROAS.", author: "Steven Incontrera", role: "Director of Marketing" },
    tags: ["b2b", "high-ticket", "lead-gen", "google", "manufacturing"],
  },
  {
    id: "jive-software",
    client: "Jive Software",
    industry: "Enterprise SaaS",
    headline: "827% decrease in cost per SQL",
    result: "827%",
    resultLabel: "Cost per SQL reduction",
    desc: "Rebuilt account structure for this enterprise collaboration platform, dropping the cost of a Sales Qualified Lead by more than 8x.",
    quote: null,
    tags: ["saas", "enterprise", "b2b", "lead-gen", "collaboration", "google"],
  },
  {
    id: "turnpoint-services",
    client: "TurnPoint Services",
    industry: "PE-Backed Services",
    headline: "Significant revenue scaling via PE growth playbook",
    result: "PE",
    resultLabel: "Portfolio-grade growth strategy",
    desc: "Applied a private equity growth playbook across PPC, GLSA, and Meta for this PE-backed services business, dramatically improving paid digital performance.",
    quote: { text: "Dramatically improved our paid digital efforts across PPC, GLSA, and Meta.", author: "Courtney West", role: "Growth Marketing Manager" },
    tags: ["pe-backed", "services", "google", "meta", "glsa", "lead-gen", "b2c"],
  },
  {
    id: "alludo",
    client: "Alludo",
    industry: "Software · PE-Owned",
    headline: "35% monthly SEM savings via new optimization framework",
    result: "35%",
    resultLabel: "Monthly SEM cost savings",
    desc: "Built a new optimization framework for this PE-owned software company, cutting search spend by 35% while maintaining revenue performance.",
    quote: null,
    tags: ["software", "pe-backed", "saas", "google", "optimization"],
  },
  {
    id: "miss-circle",
    client: "Miss Circle",
    industry: "Fashion · Ecommerce",
    headline: "94% purchase increase via occasion-based targeting",
    result: "94%",
    resultLabel: "Purchase increase",
    desc: "Rebuilt targeting strategy around buyer occasions and pricing psychology, nearly doubling purchases for this fashion ecommerce brand.",
    quote: null,
    tags: ["fashion", "ecommerce", "dtc", "meta", "google", "occasion-based", "b2c"],
  },
  {
    id: "riverspring-living",
    client: "RiverSpring Living",
    industry: "Senior Living · Healthcare",
    headline: "56.4% savings per lead for senior living facility",
    result: "56.4%",
    resultLabel: "Cost per lead reduction",
    desc: "Optimized lead generation campaigns for this senior living provider, cutting lead costs by more than half while maintaining intake volume.",
    quote: null,
    tags: ["healthcare", "senior-living", "lead-gen", "local", "b2c", "google"],
  },
  {
    id: "luma-health",
    client: "Luma Health",
    industry: "Telehealth · SaaS",
    headline: "96% YoY new user increase",
    result: "96%",
    resultLabel: "YoY new user growth",
    desc: "Drove near-doubling of new user acquisition for this telehealth platform using advanced Google targeting features.",
    quote: null,
    tags: ["healthcare", "telehealth", "saas", "b2b", "lead-gen", "google"],
  },
  {
    id: "sun-auto",
    client: "Sun Auto Tire & Service",
    industry: "Automotive · Multi-Location",
    headline: "Doubled store visits, 27% CPA reduction",
    result: "2x",
    resultLabel: "Store visits · 27% lower CPA",
    desc: "Unified campaign structure across multiple brands and locations, doubling in-store visits while cutting the cost of each visit.",
    quote: null,
    tags: ["automotive", "local", "multi-location", "google", "glsa", "services"],
  },
  {
    id: "diggerland-usa",
    client: "Diggerland USA",
    industry: "Theme Park · B2C",
    headline: "152% YoY ROAS increase via YouTube optimization",
    result: "152%",
    resultLabel: "YoY ROAS increase",
    desc: "Rebuilt YouTube strategy for this unique theme park experience, more than doubling ROAS year-over-year.",
    quote: null,
    tags: ["entertainment", "b2c", "youtube", "local", "seasonal", "consumer"],
  },
];

// Industry → tag mapping for auto-matching
export const INDUSTRY_TAG_MAP = {
  "ecommerce-fashion":    ["ecommerce", "fashion", "dtc", "meta", "google"],
  "ecommerce-luxury":     ["ecommerce", "luxury", "jewelry", "dtc"],
  "ecommerce-general":    ["ecommerce", "dtc", "google", "meta"],
  "ecommerce-sports":     ["ecommerce", "sports", "consumer"],
  "saas-b2b":             ["saas", "b2b", "lead-gen", "crm"],
  "saas-enterprise":      ["saas", "enterprise", "b2b", "lead-gen"],
  "media-publishing":     ["media", "publishing", "brand", "subscriptions"],
  "media-entertainment":  ["media", "entertainment", "subscriptions"],
  "services-home":        ["services", "home-services", "lead-gen", "local"],
  "services-professional":["b2b", "services", "lead-gen", "agency"],
  "services-pe-backed":   ["pe-backed", "services", "lead-gen"],
  "healthcare":           ["healthcare", "lead-gen", "google"],
  "pharma":               ["pharma", "healthcare", "b2b", "regulated"],
  "legal":                ["b2b", "services", "lead-gen", "high-ticket"],
  "fintech":              ["fintech", "b2b", "saas", "lead-gen"],
  "automotive":           ["automotive", "local", "google"],
  "nonprofit":            ["nonprofit", "brand", "google"],
  "manufacturing":        ["manufacturing", "b2b", "lead-gen"],
  "real-estate":          ["real-estate", "lead-gen", "local", "google"],
  "agency-naming":        ["b2b", "services", "brand", "lead-gen", "high-ticket"],
  "agency-marketing":     ["b2b", "agency", "services", "lead-gen"],
  "education":            ["b2c", "lead-gen", "google", "subscriptions"],
  "consumer-brand":       ["consumer", "b2c", "meta", "ecommerce"],
};
